[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "styletts2"
version = "0.1.0"
description = "StyleTTS2: TTS through style diffusion and adversarial training with large speech language models"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["TTS", "CLI"]
authors = [
  { name = "Aidan Pine", email = "Aidan.Pine@nrc-cnrc.gc.ca" },
  { name = "Yinghao Aaron Li" }
]
maintainers = [
  { name = "Aidan Pine", email = "Aidan.Pine@nrc-cnrc.gc.ca" },
  { name = "Eric Joanis", email = "Eric.Joanis@nrc-cnrc.gc.ca" }
]
classifiers = [
  "Intended Audience :: Developers",
  "Intended Audience :: Education",
  "Intended Audience :: End Users/Desktop",
  "Intended Audience :: Other Audience",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: MacOS :: MacOS X",
  "Operating System :: MacOS",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python",
  "Programming Language :: Unix Shell",
  "Development Status :: 4 - Beta",
  "Topic :: Multimedia :: Sound/Audio :: Speech",
  "Typing :: Typed",
]
requires-python = ">=3.10, <3.13"
dependencies = ["everyvoice==0.5.0"]

[project.optional-dependencies]
dev = [
  "everyvoice[dev]",
  "everyvoice[test]",
]
[project.scripts]
styletts2 = "styletts2.cli:app"

# ---------------------------------------------------------------------------
# uv configuration
# ---------------------------------------------------------------------------

[tool.isort]
known_first_party = "styletts2"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
ensure_newline_before_comments = true

[tool.mypy]
files = "styletts2"
ignore_missing_imports = true
plugins = ["pydantic.mypy", "numpy.typing.mypy_plugin"]
check_untyped_defs = false
explicit_package_bases = true

# ---------------------------------------------------------------------------
# pytest
# ---------------------------------------------------------------------------

[tool.pytest.ini_options]
testpaths = ["styletts2/tests"]
